# Generated by Django 4.0.3 on 2022-06-14 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shamim', '0004_tag_order_customer_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tag',
            field=models.ManyToManyField(to='shamim.tag'),
        ),
    ]
