# Generated by Django 4.0.3 on 2022-06-14 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shamim', '0005_order_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tag',
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(to='shamim.tag'),
        ),
    ]
